version: '3.8'

services:
  kong:
    image: kong:3.6
    container_name: kong
    ports:
      - "8000:8000"  # Public (proxy)
      - "8001:8001"  # Admin API
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
